### PR TITLE
InputManager class

### PR DESCRIPTION
**Pull request by bradjamesgrant**
* Created InputManager class inside Manager folder
* All inputs are  now checked for inside the InputManager class
* When a button is pressed, a delegate specific to that button is run
	* for example, when 'e' is pressed, a EKey() delegate function runs. Any function 'listening' to this broadcast will run their respective function
* Any function from any class can subscribe to a specific input event
	* Usually want to register listener in Start function
	* If script is on player, use GetComponent<InputManager>().EKey += PickupItem
	* If not, use GameObject.Find("Player").GetComponent<InputManager>().EKey += PickupItem
	* The PickupItem method will now be registered as a listener to a E key press
* ToggleInventory was taken out from PlayerPickupItems and a listener was put directly in the InventoryManager class
* InputManager now listens to E, B, LeftMouseClick, RightMouseClick, and one for any movement (WASD or Jump)
* movement delegate calls PlayerMovement's movement function
* B delegate calls InventoryManager's DisplaySwitch function
* E delegate calls PlayerPickUpItems' PickUpOperation function

Minor changes
* Improved scaling to Inventory
* Added knife model, and dropped it in sampleScene
* Moving inv to player from UI (KAI)

Test scene by ensuring all keys work still and slots in inventory are hugged by borders

**UPDATE**

*Fixed 3 bugs*
	
- Delegates could be null before called
- Player would try to pick up null (when camera was facing sky)
- Player movement would feel slippery

2 new commits

-Adding new glowing material to weapon
-can be picked up and put in inventory now (any prefab in scene with tag of t1, a TestWeapon script and a collider can)

### CODE REVIEW

**Review by nodonogh — APPROVED** [review]
_All good, no errors. Works perfectly_ - **Ignore**

**Review by nodonogh — CHANGES_REQUESTED** [review]
Sorry, forgot to pull files, my bad. I have 1 error:
image

**Comment by bradjamesgrant** [comment]
fixed!

**Review by kaizhilam — CHANGES_REQUESTED** [review]
Player Movement feels weird, it's like the player is sliding on ice. When I let go any movement key, it'll take like half a second before the player stops

**Comment by bradjamesgrant** [comment]
Fixed Inventory bug where items would only be held in every second slot

**Review by nodonogh — CHANGES_REQUESTED** [review]
Hey Brad, all seems to work on SampleScene, but I've got a few issues with MainLevel:
image
Player seems to be stuck up there too

**Comment by bradjamesgrant** [comment]
Thanks again nick! Fixed. Also fixed bug where players gravity wouldn't update unless WASD was input by reverting movement to how it was. Deleted movement delegate from InputController

**Review by nodonogh — APPROVED** [review]
Seems to have done the job! Good stuff

**Review by kaizhilam — APPROVED** [review]

**Pull request merged**
