### PR TITLE
Armbow fully integrated, weapon wielded will now mirror inventory

### PR DESCRIPTION
**Pull request by bradjamesgrant**
* Adding clear materials for knife and armbow (not final look)
* Added armbow prefab and script
* Armbow glows
* Players attack method will now entirely depend on which weapon is being wielded
* Pressing 1 will equip weapon in slot 1 (if any). Same for 2 and 3
* Armbow can now be wielded, attached to forearm bone
* Script on armbone added so it can be found easily and its clearer in code which bone is being searched for
* Swapping inv weapons will update player weapon is selected hotbar index weapon is changed
* If item added to slot where player is indexed at, it will wield that weapon
* Each SlottedItem can now provide a local position, local rotation, local scale and bone index to add the item to
* 0 bone index refers to hand, -1 refers to hands parent bone (the arm)
* InputManager now broadcasts when 1,2 or 3 is pressed passing in the number pressed (int) as parameter
* Inventory now holds the value of which index of the hotbar the player has selected
* Scripts put on weapon prefabs now require the prefab in the inspector (for instantiation)

--Known bugs/issues--
* StateMachine will cause bulk errors after a certain time
* No visualisation for which slot player is on in hotbar

--How to test this branch--
* Pick up armbow and knife
* Player should have slot1 item equipped
* if you swap slot1 for the other weapon, player should switch weapon on hand
* if you drag weapon off slot1, it should unequip the weapon
* Pressing 2 will equipped weapon in slot2
* Attacking with knife should be able to kill dino
* Attacking with armbow should print message to log

### CODE REVIEW

**Comment by bradjamesgrant** [comment]
- Fixed NullReference when player would place item that they are wielding into inv
- Fixed incorrect attack functions running for weapons
- Fixed bug where player could pick up items that had already been picked up

**Review by nodonogh — APPROVED** [review]
All seems to work as described

**Comment by bradjamesgrant** [comment]
--Updated--
* new png for highlighted slot (thanks to David T)
* hotbar slot that player has selected will now be a different colour
* Chase state can now return to wander state

--fixed bugs--
* Dino's raycasting would always hit itself

--known bugs/issues--
* Dino can see player through walls
* Statemachine may still produce errors after a while

--How to test this update--
* Make sure by pressing 1,2 or 3, the appropriate slot in hotbar will be highlighted
* Make sure all previous features work as intended

**Comment by bradjamesgrant** [comment]
--Updated--

* Animations now run much smoother, and don't interfere with each other (still problem when spamming jump)
* Player will no longer be able to jump while mid-roll
* Player should no longer be able to roll in mid-air
* AnimationManager has more functionality

1. Can now reset all animations to false
2.  Can now reset all animations except for those specified
3. Can check if an animation is running at all
4. Will now hold the animation info in public clipInfo variable (clipInfo.clip.name to retrieve name of active animation)

--known bugs/issues--
* Spam jumping will cause the jump animation to sometimes be very delayed

--bug fixes--
* Player would have a delayed roll on pressing CTRL
* Player would switch from jump animation into idle animation (very briefly) even though they were still sprinting

--How to test this update--
* Play around with animations

**Review by kaizhilam — APPROVED** [review]

**Pull request merged**
