### PR TITLE
Programming/david z

### PR DESCRIPTION
**Pull request by DavidZhang23**
invisible but still have a collision .
invisible at the screen but still have the active ability.
invisible to the enemy.
(automatically activated at start temporarily, will fix it later)

### CODE REVIEW

**Comment by kaizhilam** [comment]
Bad news dude, you might have to redo the invisibility, just a heads up. Backup your code so you can just copy stuff off it

**Review by bradjamesgrant — APPROVED** [review]
**fixed small merge conflicts for you. Invisibility seems to work. Removing it from the ability array makes the player visible again. Enemy doesn't chase player when they are invisible, v nice**

**Comment by quandarealest** [comment]
Good day, David. It seems like you have a conflict with `Player.prefab` file. Please help me to resolve it in order to review and approve your work. Cheers!

**Comment by bradjamesgrant** [comment]
Hey David please keep your invisibility code, but I've deleted the ability system because we are changing it to a weapon system instead. Eventually one of the weapons will have an invisibility ability attached so we will need it eventually, just not now

**Comment by DavidZhang23** [comment]
Ok,copy that😁,thx for the help, is the PR ok now? I was in lecture this morning.

David Zhang

________________________________

**Pull request closed without merging**
