### PR TITLE
PauseMenu & MainMenu

### PR DESCRIPTION
**Pull request by galgame-sh**
Press esc to pause the game
Created a MainMenu to access
Screen Shot 2019-04-30 at 4 22 53 pm
Screen Shot 2019-04-30 at 4 23 07 pm

### CODE REVIEW

**Review by kaizhilam — CHANGES_REQUESTED** [review]
Bug
- Enemy flies up when unpause
- camera still moving when paused
- Quit button isn't working
- When you press to menu, and click new game again, the game freezes

**Comment by galgame-sh** [comment]
> Bug
> 
> * Enemy flies up when unpause
> * camera still moving when paused
> * Quit button isn't working
> * When you press to menu, and click new game again, the game freezes

Quit button will only work once the game built

**Comment by kaizhilam** [comment]
Still need to address theese bugs
- Enemy flies up when unpause
- camera still moving when paused
- When you press to menu, and click new game again, the game freezes

**Comment by galgame-sh** [comment]
> Still need to address theese bugs
> 
> * Enemy flies up when unpause
> * When you press to menu, and click new game again, the game freezes


> * Enemy flies up when unpause
Didn't have the problem in my machine
> * camera still moving when paused
the camera problem fixed 

> * When you press to menu, and click new game again, the game freezes
the game will resume when press esc again, but not sure how to fix it

**Comment by kaizhilam** [comment]
image

**Comment by kaizhilam** [comment]
Redo this in Unity 3.6 please. And don't drag and drop because it'll contain stuff from Unity 3.11

**Comment by kaizhilam** [comment]
Soz, My fault, there was 2 branch

**Comment by bradjamesgrant** [comment]
just commit what you have. When I add my part of code it should work then

**Comment by galgame-sh** [comment]
> just commit what you have. When I add my part of code it should work then

Commited

**Review by kaizhilam — APPROVED** [review]

**Comment by bradjamesgrant** [comment]
I can't resolve these conflicts :/

EDIT: Best thing to do is make everything prefabs and save them and the camera script on your desktop or similar
Then reclone the project, and add into the project files the prefabs and add your camera code to the existing script. 
put your prefabs into the scene if needed, then push

**Pull request closed without merging**
