### PR TITLE
Fixed underwater script

### PR DESCRIPTION
**Pull request by nodonogh**
Best way to test:

- Go underwater at lake 1
- Walk toward lake 7 after that
- If you get to lake 7 and it works correctly, it's all good

Changes:
- Removed certain texturing i was testing due to merge conflict

### CODE REVIEW

**Comment by quandarealest** [comment]
Hi Nick, could you help me resolve your conflicts on your branch? Also can you add some pictures on your description. Thank you and have a nice day.

**Review by bradjamesgrant — APPROVED** [review]
functions as it should

**Review by kaizhilam — APPROVED** [review]

**Comment by kaizhilam** [comment]
I approved the review because everything is working fine. But there are some weird game object in the heirachy, just a heads up. IDK if it's meant to be there
image

**Review by kaizhilam — APPROVED** [review]
DAMN. SHIT LOOKS AMAZING SON

**Pull request merged**
