### PR TITLE
fixing gamebreaking bug, now spawns dinos

### PR DESCRIPTION
**Pull request by bradjamesgrant**
fixed bug, spawner now spawns dinos
dinos
Bump up the spawner count to test framerate

### CODE REVIEW

**Review by Redlyu — COMMENTED** [review]
Should the dions get to move? They are not moving now.
Can not blink.

**Comment by bradjamesgrant** [comment]
Their prefab has no monobehaviour so they don't. You could add an enemyAI script to them and they will chase you, pretty sure anyway.

**Comment by Redlyu** [comment]
image
Still not move. Do i forget any steps?

**Comment by bradjamesgrant** [comment]
I'm working on it. turns out theres a lot more steps to it

**Pull request closed without merging**
