### PR TITLE
spawning working with scene accommodating immediate testing

### PR DESCRIPTION
**Pull request by bradjamesgrant**

### CODE REVIEW

**Review by kaizhilam — APPROVED** [review]
It's raining enemies XD. I'll approve it, I'll try to find a way to stop that error from popping up. Just make sure spawner game object isn't directly on player game object. the enemy that spawns launches the player into space!

**Comment by KyleGTeng** [comment]
Is work

**Comment by kaizhilam** [comment]
I'm just gonna close this because its been up for ages. and I haven't tested any of the new commits

**Review by Redlyu — APPROVED** [review]
No errors. Just find i can not get out when i fall to the bottom of the lake.

**Pull request merged**
