### PR TITLE
Added Climbing 

### PR DESCRIPTION
**Pull request by sfederic**
C to toggle climbing against objects with the "Climb" tag.

### CODE REVIEW

**Comment by Redlyu** [comment]
It is working, but can not climb over the wall and no specific climbing action

**Comment by bradulz** [comment]
No way to detach from the wall other than by reaching the top

**Comment by bradjamesgrant** [comment]
It would be good if the player would automatically detach from the wall when they reach the ground but it's good

**Review by bradjamesgrant — APPROVED** [review]

**Review by nodonogh — APPROVED** [review]
Works great!

**Pull request merged**
