### PR TITLE
dragging and dropping functionality for Inventory

### PR DESCRIPTION
**Pull request by bradjamesgrant**
* State.cs renamed to EnemyAIState.cs
* Inventory now invisible on game load
* Turned down dino sounds
* Added more functions for InventoryManager, namely to do with searching for slot information
* Slot.cs how implements IDragHandler and IEndDragHandler for dragging and dropping
* When player drags one slots contents over another, the initial slot will call InventoryManager to swap the contents
* If not dragged onto slot, will return itself to original position

--How to test this pull request--
Pick up items from the ground
Drag from hotbar slot to another hotbar slot
Drag from hotbar slot to inv slot
Drag from inv slot to hotbar slot
Make sure a stack of 2 swaps completely with a stack of 1
Place item on slot where another item was recently kept
Letting go of drag when not over a slot should return the item to its original position
(in future ill make player able to stack similar items on top of each other [if doesn't go over capacity])

### CODE REVIEW

**Review by nodonogh — CHANGES_REQUESTED** [review]
Hey Brad, I found a bug when picking up 1 weapon. I pick it up, then move it to the slot in the picture, then when I try to pickup another weapon, I get the error at the bottom:

image

Closer look at error:
image

**Comment by kaizhilam** [comment]
I'm having the same error as Nick as well. To get the same error, pick up a weapon, move the weapon from the hotbar to the inventory, and then try and pick up a second weapon

**Comment by bradjamesgrant** [comment]
* fixed 3 OutOfBoundsExceptions concerning picking up new weapon with one already in inventory

**Review by kaizhilam — APPROVED** [review]

**Review by nodonogh — CHANGES_REQUESTED** [review]
Ok so this is a weird one. Pickup all weapons. 
1. Use the first hot bar slot to store a stack of 2 weapons. 
2. Then, swap it for the weapon with just 1 in the stack. 
3. Swap the slot again, (i.e. put the stack of 2 back where the stack of 1 is), which puts the 2 stack back.
4. Swap out the stack of 2 for an empty slot after that and it duplicates. 
5. Try to swap out the duplicated stack for an empty spot, then it disappears!
Honestly not sure what's happening there

**Comment by bradjamesgrant** [comment]
* fixed bug where a slot could contain 2 itemUI components

**Review by nodonogh — APPROVED** [review]

**Pull request merged**
