### PR TITLE
Programming/kyle gt

### PR DESCRIPTION
**Pull request by KyleGTeng**
Tent Added

### CODE REVIEW

**Review by nodonogh — APPROVED** [review]
All works assuming you are supposed to be able to walk through the tent like this:
image

**Comment by Redlyu** [comment]
Sorry man i do not find the tent. Did i miss some steps? I opened both Mainlevel scenes and  sample scenes. The hierarchy shows no tent also.

**Review by quandarealest — APPROVED** [review]
I added collider to the tent for you. Everything is fine but where did you leave the tent in the folder? I can't find to use it. Great job Teng!

**Comment by KyleGTeng** [comment]
should be in Model-Architecture-tent.fbx

**Pull request merged**
