### PR TITLE
Rough Animator and combat hitbox implementation.

### PR DESCRIPTION
**Pull request by sfederic**

### CODE REVIEW

**Review by bradjamesgrant — COMMENTED** [review]
2 Things
* Do you mind calling the animation class AnimationManager to fit with the theme we got?
* I can help you with tomorrow but setting binding the inputs to the inputcontroller too would be good

**Review by quandarealest — CHANGES_REQUESTED** [review]
Hey @sfederic , I had these error whenever I clicked hit. Can you resolve it so that we can merge your branch. 

Capture

**Review by quandarealest — DISMISSED** [review]

**Review by nodonogh — CHANGES_REQUESTED** [review]
Couple of things:
1. Need to address these issues in SampleScene (easy fix):
image

2. Cant pickup items or open inventory on SampleScene:
image

Inventory still opens on MainLevel though and I suppose that's the main thing

**Comment by quandarealest** [comment]
> 
> 
> Couple of things:
> 
>     1. Need to address these issues in SampleScene (easy fix):
>        image
> 
>     2. Cant pickup items or open inventory on SampleScene:
>        image
> 
> 
> Inventory still opens on MainLevel though and I suppose that's the main thing

Tks @nodonogh for reminding me the errors

**Comment by bradjamesgrant** [comment]
All added

**Pull request closed without merging**
