### PR TITLE
Limit blink vertical distance

### PR DESCRIPTION
**Pull request by kaizhilam**
Player can't blink vertically if it is 8 units higher

### CODE REVIEW

**Comment by quandarealest** [comment]
I'm testing your PR but it seems like there is something wrong. `NullReferenceException: Object reference not set to an instance of an object FirstEnemy..ctor () (at Assets/Scripts/Enemy/FirstEnemy.cs:10) UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)` @kaizhilam 

image

**Comment by kaizhilam** [comment]
That's brad's code. he need to push it to master first before I can

**Review by bradjamesgrant — APPROVED** [review]
niceu

**Review by quandarealest — APPROVED** [review]
Legit af. Good works, @kaizhilam !

**Pull request merged**
