### PR TITLE
enable gpu instancing, swimming, dodge when running, change anchor of…

### PR DESCRIPTION
**Pull request by MYLi-233**
1. Enable GPU instancing of the underwaterEffect, green, knife, not underwater material file.
2. Swimming (float by pressing space, the lakes should bind the underwater.cs)
3. The anchor of the knapsack is centre now, instead of stretch.
4. A little addition: currently, the character only can dodge when she is running.

### CODE REVIEW

**Review by nodonogh — CHANGES_REQUESTED** [review]
It works ok, but double jump seems to break it a bit. Once you get double jump, the player will double jump from only pressing space once, which makes the swimming a bit redundant. Just need to fix the double jump ability, and probably disable the double jump when in water

**Comment by MYLi-233** [comment]
> It works ok, but double jump seems to break it a bit. Once you get double jump, the player will double jump from only pressing space once, which makes the swimming a bit redundant. Just need to fix the double jump ability, and probably disable the double jump when in water

I am so sorry. Now I push the new staff.

**Review by nodonogh — APPROVED** [review]
Works great! Probably better to disable the ability to double jump while in water, but I anticipate that would cause some issues, so all good! Nice work

**Review by kaizhilam — APPROVED** [review]
Nice!

**Pull request merged**
