### PR TITLE
More behaviour, new model, enemies can be killed

### PR DESCRIPTION
**Pull request by bradjamesgrant**
- Created enemy layer mask for raycasting
- Created wander behaviour for enemy

### CODE REVIEW

**Comment by quandarealest** [comment]
Hi @bradulz , there is a conflict of `SampleScene.unity` on your branch with master branch. Could you help me to check it out? Ty.

image

**Comment by bradjamesgrant** [comment]
should be alright now (y)

**Review by kaizhilam — APPROVED** [review]
Weird wondering, but okay

**Comment by bradjamesgrant** [comment]
in new commit: 
- changed health to float
- enemy can check if its dead
- enemy can take damage
- enemies take damage when come into contact with projectile
- added 'attack' tag to projectiles, used to help with collision checking
- stop using scriptable obj for enemy stats. Set up in constructor instead so that spawned dinos have health set correctly

**Comment by bradjamesgrant** [comment]
new commit:

- added sunny model, to pair with flying ability

**Review by KyleGTeng — APPROVED** [review]

**Pull request merged**
