### PR TITLE
Programming/zeyao 2

### PR DESCRIPTION
**Pull request by lizeya12**
Add cooldown in each hot bar slot in sample scene
Add health bar in sample scene

### CODE REVIEW

**Comment by kaizhilam** [comment]
image
I'm getting this error

**Comment by bradjamesgrant** [comment]
image

this seems to fix it

Also make sure you save the HP to the UI:

1. Click on UI in hierarchy
2. In the inspector, click override
3. Click apply all

Just know that things in the hierarchy with the + symbol next to them aren't being saved, so although you may have it in MainLevel, it won't be updated in SampleScene

MAKE SURE YOU SAVE THE SCENE TOO

**Comment by bradjamesgrant** [comment]
Errors have been fixed
When testing this branch just make sure that each hotbar slot in the hierarchy has a CDMask.
Also make sure the UI prefab has HealthBar->Hp in it

**Review by bradjamesgrant — APPROVED** [review]

**Review by Redlyu — APPROVED** [review]
All good, just find two HealthBar in hierarchy
image

**Pull request merged**
